apiVersion: apps/v1
kind: Deployment
metadata:
  name: mca
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mca
  template:
    metadata:
      labels:
        app: mca
    spec:
      containers:
      - image: ghcr.io/shaileshjk/mca:sha256-bb1ce6e018ea06ed19e997602ec651acf8e14145d0663ed2d90ea044370cef2e.sig
        name: mca
        ports:
        - containerPort: 8080
        
